[package]
name = "contentcraft"
version = "0.1.0"
edition = "2021"

[lib]
name = "contentcraft_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "contentcraft"
path = "src/main.rs"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
